name: '🧹 Cleanup'
description: 'Clean working directory on self-hosted runners'

runs:
  using: composite
  steps:
    - id: step-1
      name: '🧹 Clean working directory'
      if: ${{ always() }} # Run even if the job fails or is canceled
      shell: bash
      # TODO: evaluate rm -rf "${{ github.workspace }}"
      run: |
        echo "🧹 Cleaning working directory..."
        rm -rf ./*
